name: CI

on:
  push: {}

jobs:
  ConditionalActions:
    name: AppCenter for ${{ matrix.targetPlatform }} in ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      APK_PATH: ${{ format('{0}/testApk.apk', github.workspace) }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Install node.js
        uses: zendesk/setup-node@v2.0.0
        with:
          node-version: 12
      - name: Install AppCenter CLI
        run: npm install -g appcenter-cli@2.5.4

      - name: Publish apk to AppCenter
        env:
          APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN }}
          FILE_PATH: ${{ env.APK_PATH }}
        run: |
          chmod +x Scripts/appcenter.sh
          ./Scripts/appcenter.sh