on:
  push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      PR_FROM_TRANSLATIONS: ${{ contains(github.event.pull_request.title, '[i18n]') }}
      CHECK_NEGATIVE: ${{ !contains(github.event.pull_request.title, '[i18n]') }}
      PR_CREATOR: ${{ github.actor }}
      REVIEW_STATE: ${{ github.event.review.state }}
    steps:
      - run: |
          echo "branch: ${{ github.head_ref }}"
          echo "context: $GITHUB_CONTEXT"
          echo "is it from translations?: $PR_FROM_TRANSLATIONS"
          echo "negative available?: $CHECK_NEGATIVE"
          echo "pr created by: $PR_CREATOR"
          echo "PR review state: $REVIEW_STATE"

  printIfApproved:
    runs-on: ubuntu-latest
    env:
      REVIEW_STATE: ${{ github.event.review.state }}
    steps:
      - run: |
          echo "PR Approved!"
          echo "PR review state: $REVIEW_STATE"