name: CI

on:
  push: {}

jobs:
  name: Testing conditional env var
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS
          - Android
        unityVersion:
          - 2018
          - 2019
        env:
          if: matrix.targetPlatform == 'iOS'
            ARTIFACT_NAME: ${{ format('iOS_unity_{0}', matrix.unityVersion) }}
          if: matrix.targetPlatform == 'Android'
            ARTIFACT_NAME: ${{ format('build_{0}_Android', matrix.unityVersion) }}
    steps:
      - uses: actions/checkout@v2
      - run: echo $ARTIFACT_NAME
