name: DependencyTesting

on:
  push: {}

jobs:
  Job1:
    name: Job 1 - ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS
          - Android
    steps:
      - uses: actions/checkout@v2
      - run: echo "This is Job 1 ${{ matrix.targetPlatform }}"

  Job2:
    name: Job 2 - ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS
          - Android
    steps:
      - uses: actions/checkout@v2
      - run: echo "This is Job 2 ${{ matrix.targetPlatform }}"

  FollowUpJob:
    name: This is the follow up job
    runs-on: ubuntu-latest
    needs: 
      - Job1
      - Job2
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2018
          - 2019
    env:
      BUILDS_PATH: ${{ format('{0}/build_{1}_iOS', github.workspace, matrix.unityVersion) }}

    steps:
      - uses: actions/checkout@v2
      - run: echo "This is a follow up job for ${{ matrix.unityVersion}}"