name: CI

on:
  push: {}

jobs:
  ConditionalActions:
    name: Getting git branch and other references
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      
      - name: Get current branch name
        run: echo ${GITHUB_REF#refs/heads/}

      - name: Get github PR number
        run: echo ${{ github.event.number }}
