on:
  pull_request_review:
    types: [submitted]
jobs:
  printApprovedReview:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PR Approved"
          echo "branch: ${{ github.head_ref }}"