on:
  pull_request_review:
    types: [APPROVED]
jobs:
  printApprovedReview:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "PR Approved"
        echo "branch: ${{ github.head_ref }}"