on:
  pull_request_review:
    types: [submitted]
jobs:
  printApprovedReview:
    runs-on: ubuntu-latest
    steps:
      - name: Print Approval
        if: github.event.review.state == 'approved'
      - run: |
          echo "PR Approved"
          echo "branch: ${{ github.head_ref }}"