on:
  push: {}
  
jobs:
  verifyConditionalEnvVar:
    name: Set env var based on matrix value - ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [iOS, Android]
    env:
      SECRET_KEY_ANDROID: ${{ secrets.SECRET_KEY_Android }}  
    steps:
      - uses: actions/checkout@v2
      - run: | 
          echo "iOS secret exists: ${{ secrets.SECRET_KEY_IOS != 0 }}"
          echo "Android secret exists: ${{ secrets.SECRET_KEY_Android != 0 }}"
          echo "iOS env var exists: ${{ env.SECRET_KEY_IOS != 0 }}"
          echo "Android env var exists: ${{ env.SECRET_KEY_ANDROID != 0 }}"
          
  
  verifyCaseInsensitiveSecretLookup:
    name: Read secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if secret exists, and make sure its case insensitive. Should return true for all cases
        run: |
          echo "${{ secrets.SECRET_KEY != 0 }}"
          echo "${{ secrets.SECRET_key != 0 }}"
          echo "${{ secrets.secret_key != 0 }}"
      - name: print secret mixed keys
        run: echo "${{ secrets.SECRET_key != 0 }}"
