on:
  push: {}
  
jobs:
  verifyCaseInsensitiveSecretLookup:
    name: Read secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if secret exists, and make sure its case insensitive. Should return true for all cases
        run: |
          echo "${{ secrets.SECRET_KEY != 0 }}"
          echo "${{ secrets.SECRET_key != 0 }}"
          echo "${{ secrets.secret_key != 0 }}"
      - name: print secret mixed keys
        run: echo "${{ secrets.SECRET_key != 0 }}"
  verifyAppending:
    name: AppendStringToSecret - ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [iOS, Android]
    steps:
      - uses: actions/checkout@v2
      - name: Check if we can append a matrix value to a secret. Android exists, iOS doesn't.
        env:
          SECRET_KEY: ${{ secrets.SECRET_key_${{ matrix.platform }} }}
        run: echo "${{ env.SECRET_KEY != 0 }}"
