on:
  push: {}
  
jobs:
  verifyConditionalEnvVar:
    name: Set env var based on matrix value - ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [iOS, Android]
        include:
          - platform: Android
            SECRET_KEY: ${{ secrets.SECRET_KEY_Android }}
          - platform: iOS
            SECRET_KEY: ${{ secrets.SECRET_KEY_iOS }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ matrix.SECRET_KEY != 0 }}"
