on:
  push: {}
  
jobs:
  my_job:
    name: Read secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print secret uppercase
        run: echo "${{ secrets.SECRET_KEY }}"
      - name: print secret mixed keys
        run: echo "${{ secrets.SECRET_key }}"
      - name: print secret lowercase
        run: echo "${{ secrets.secret_key }}"
